name: Only Publish Minor

on:
  workflow_dispatch:
    inputs:
      npm_otp:
        description: enter npm otp
        required: true

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo:  
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm update
      - run: npm install
      - run: npm test
      - run: npm publish --otp ${{github.event.inputs.npm_otp}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} 
