name: Node.js Package

on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo:  
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm update
      - run: npm audit fix
      - run: npm install
      - run: npm test
      - run: git config --global user.email "montumodi@gmail.com"
      - run: git config --global user.name "Ashish Modi"
      - run: git commit -m "Add changes" -a
        env:	
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - run: npm version minor
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}} 
